-- AI Guardian MySQL Schema
-- Run this file once to set up the database

CREATE DATABASE IF NOT EXISTS ai_guardian;
USE ai_guardian;

-- Emergency incidents logged whenever an emergency is triggered
CREATE TABLE IF NOT EXISTS emergency_incidents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    emergency_type VARCHAR(50) NOT NULL,
    description TEXT,
    gps_coordinates VARCHAR(100),
    location VARCHAR(255),
    status ENUM('active', 'resolved') DEFAULT 'active',
    source ENUM('web', 'python') DEFAULT 'web',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Volunteer requests that appear in the Volunteer Dashboard
CREATE TABLE IF NOT EXISTS volunteer_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    emergency_type VARCHAR(50) NOT NULL,
    location VARCHAR(255) NOT NULL,
    description TEXT,
    status ENUM('active', 'accepted', 'resolved') DEFAULT 'active',
    distance DECIMAL(5,2),
    incident_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE SET NULL
);

-- Emergency cards generated by web or Python server
CREATE TABLE IF NOT EXISTS emergency_cards (
    id INT AUTO_INCREMENT PRIMARY KEY,
    emergency_type VARCHAR(50) NOT NULL,
    gps_coordinates VARCHAR(100),
    description TEXT,
    contact_info VARCHAR(255),
    timestamp VARCHAR(100),
    source ENUM('web', 'python') DEFAULT 'web',
    incident_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE SET NULL
);

-- Seed some initial volunteer requests for testing
INSERT INTO emergency_incidents (emergency_type, description, location, status, source) VALUES
('fire', 'Smoke visible from building, evacuation in progress', '123 Main St, Downtown', 'active', 'web'),
('heart_attack', 'Person collapsed, conscious but in pain', 'Central Park, near pond', 'active', 'web'),
('cpr', 'Unconscious person, CPR in progress', '456 Oak Avenue', 'active', 'web');

INSERT INTO volunteer_requests (emergency_type, location, description, status, distance, incident_id) VALUES
('fire', '123 Main St, Downtown', 'Smoke visible from building, evacuation in progress', 'active', 0.3, 1),
('heart_attack', 'Central Park, near pond', 'Person collapsed, conscious but in pain', 'active', 0.8, 2),
('cpr', '456 Oak Avenue', 'Unconscious person, CPR in progress', 'accepted', 1.2, 3);
